version: '3.8'

services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

    network_mode: host