version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joomla5passwd
      MYSQL_DATABASE: ect
      MYSQL_USER: joomlauser
      MYSQL_PASSWORD: joomla5passwd
    ports:
      - "3306:3306"
